#include "CheapFunctions.h"
#include <fstream>//todo remove



CheapFunctions::CheapFunctions()
{
}


CheapFunctions::~CheapFunctions()
{
}

void CheapFunctions::generateADSRPow(){
    //generate function MIN_DECAY_RELEASE_VALUE^(1/x)
    //min input: 0.001 * 44100
    //max input: 10 * 44100
    //10.000 table points

    double stepsize = 44100. * 0.001;

    std::ofstream adsr_table;
    adsr_table.open("E:\\odin\\LookupTables\\adsr_pow.h");

    adsr_table << "// generated by CheapFunctions::generateADSRPow()\n";
    adsr_table << "float adsr_pow_table[" << MAX_TABLE_ADSR << "] = {";

    for(size_t i = 0; i < MAX_TABLE_ADSR; ++i){
        adsr_table << pow(0.001, 1. / (stepsize + stepsize * i));
        if(i != MAX_TABLE_ADSR - 1){
            adsr_table << ", ";
        }
    }

    adsr_table << "};";
    adsr_table.close();
}
