//! This file is autogenerated by assets/graphics/create_graphics_headers.sh
//! Do not edit this by hand

#pragma once

#include "../GlobalIncludes.h"

struct UIAssetsData {
    static std::array<const char*, 1461> Data;
};
