//! This file is autogenerated by assets/graphics/create_graphics_headers.sh
//! Do not edit this by hand

#include "UIAssetsSize.h"

std::array<size_t, 30> UIAssetsSize::Size = {
    BinaryData::background_pngSize,
    BinaryData::Filter_Bandpass12_pngSize,
    BinaryData::Filter_Bandpass24_pngSize,
    BinaryData::Filter_Combfilter_pngSize,
    BinaryData::Filter_DiodeLadder_pngSize,
    BinaryData::Filter_Formant_pngSize,
    BinaryData::Filter_Highpass12_pngSize,
    BinaryData::Filter_Highpass24_pngSize,
    BinaryData::Filter_KRG35HP_pngSize,
    BinaryData::Filter_KRG35LP_pngSize,
    BinaryData::Filter_Lowpass12_pngSize,
    BinaryData::Filter_Lowpass24_pngSize,
    BinaryData::Filter_Ringmod_pngSize,
    BinaryData::Filter_SEM12_pngSize,
    BinaryData::FX_Chorus_pngSize,
    BinaryData::FX_Delay_pngSize,
    BinaryData::FX_Flanger_pngSize,
    BinaryData::FX_Phaser_pngSize,
    BinaryData::FX_Reverb_pngSize,
    BinaryData::Oscillator_Analog_pngSize,
    BinaryData::Oscillator_ChipDraw_pngSize,
    BinaryData::Oscillator_Chiptune_pngSize,
    BinaryData::Oscillator_FM_pngSize,
    BinaryData::Oscillator_Multi_pngSize,
    BinaryData::Oscillator_Noise_pngSize,
    BinaryData::Oscillator_PM_pngSize,
    BinaryData::Oscillator_SpecDraw_pngSize,
    BinaryData::Oscillator_Vector_pngSize,
    BinaryData::Oscillator_WaveDraw_pngSize,
    BinaryData::Oscillator_Wavetable_pngSize,
};
