//! This file is autogenerated by assets/graphics/create_graphics_headers.sh
//! Do not edit this by hand

#include "UIAssetsData.h"

std::array<const char*, 30> UIAssetsData::Data = {
    BinaryData::background_png,
    BinaryData::Filter_Bandpass12_png,
    BinaryData::Filter_Bandpass24_png,
    BinaryData::Filter_Combfilter_png,
    BinaryData::Filter_DiodeLadder_png,
    BinaryData::Filter_Formant_png,
    BinaryData::Filter_Highpass12_png,
    BinaryData::Filter_Highpass24_png,
    BinaryData::Filter_KRG35HP_png,
    BinaryData::Filter_KRG35LP_png,
    BinaryData::Filter_Lowpass12_png,
    BinaryData::Filter_Lowpass24_png,
    BinaryData::Filter_Ringmod_png,
    BinaryData::Filter_SEM12_png,
    BinaryData::FX_Chorus_png,
    BinaryData::FX_Delay_png,
    BinaryData::FX_Flanger_png,
    BinaryData::FX_Phaser_png,
    BinaryData::FX_Reverb_png,
    BinaryData::Oscillator_Analog_png,
    BinaryData::Oscillator_ChipDraw_png,
    BinaryData::Oscillator_Chiptune_png,
    BinaryData::Oscillator_FM_png,
    BinaryData::Oscillator_Multi_png,
    BinaryData::Oscillator_Noise_png,
    BinaryData::Oscillator_PM_png,
    BinaryData::Oscillator_SpecDraw_png,
    BinaryData::Oscillator_Vector_png,
    BinaryData::Oscillator_WaveDraw_png,
    BinaryData::Oscillator_Wavetable_png,
};
