//! This file is autogenerated by assets/graphics/create_graphics_headers.sh
//! Do not edit this by hand

#pragma once

namespace UIAssets {

enum class Indices : int {
    background,
    Filter_Bandpass12,
    Filter_Bandpass24,
    Filter_Combfilter,
    Filter_DiodeLadder,
    Filter_Formant,
    Filter_Highpass12,
    Filter_Highpass24,
    Filter_KRG35HP,
    Filter_KRG35LP,
    Filter_Lowpass12,
    Filter_Lowpass24,
    Filter_Ringmod,
    Filter_SEM12,
    FX_Chorus,
    FX_Delay,
    FX_Flanger,
    FX_Phaser,
    FX_Reverb,
    Oscillator_Analog,
    Oscillator_ChipDraw,
    Oscillator_Chiptune,
    Oscillator_FM,
    Oscillator_Multi,
    Oscillator_Noise,
    Oscillator_PM,
    Oscillator_SpecDraw,
    Oscillator_Vector,
    Oscillator_WaveDraw,
    Oscillator_Wavetable,
    NumIndices
};
}
