//! This file is autogenerated by assets/graphics/create_graphics_headers.sh
//! Do not edit this by hand

#pragma once

#include "../GlobalIncludes.h"
struct UIAssetsSize {
    static std::array<size_t, 1247> Size;
};
